"""
Infrastructure Service Ports

Architectural Intent:
- Defines port interfaces for external cloud infrastructure operations
- Ports enable swappable implementations (direct SDK, MCP adapters)
- Following Rule 2: Interface-First Development
"""

from abc import ABC, abstractmethod
from typing import Protocol, AsyncIterator
from uuid import UUID
from datetime import datetime

from domain.entities.cloud_provider import CloudProvider
from domain.entities.resource import Resource
from domain.value_objects.money import Money


class CloudProviderPort(Protocol):
    async def connect(self, provider: CloudProvider) -> bool: ...
    async def disconnect(self, provider: CloudProvider) -> bool: ...
    async def get_status(self, provider: CloudProvider) -> str: ...


class ResourcePort(Protocol):
    async def create(self, provider: CloudProvider, config: dict) -> Resource: ...
    async def start(self, resource: Resource) -> bool: ...
    async def stop(self, resource: Resource) -> bool: ...
    async def terminate(self, resource: Resource) -> bool: ...
    async def get_status(self, resource: Resource) -> str: ...
    async def update_tags(self, resource: Resource, tags: dict) -> bool: ...


class CostPort(Protocol):
    async def get_current_cost(
        self, provider_id: UUID, start_date: datetime, end_date: datetime
    ) -> Money: ...
    async def get_cost_breakdown(
        self, provider_id: UUID, start_date: datetime, end_date: datetime
    ) -> dict: ...
    async def get_forecast(self, provider_id: UUID, days: int) -> Money: ...


class ObservabilityPort(Protocol):
    async def get_metrics(
        self, provider_id: UUID, metric_name: str, start: datetime, end: datetime
    ) -> list[dict]: ...
    async def get_logs(
        self, provider_id: UUID, resource_id: UUID, start: datetime, end: datetime
    ) -> list[str]: ...
    async def get_traces(self, provider_id: UUID, trace_id: str) -> dict: ...


class IaCPort(Protocol):
    async def plan(self, provider_id: UUID, template: str) -> dict: ...
    async def apply(self, provider_id: UUID, template: str) -> dict: ...
    async def destroy(self, provider_id: UUID, template: str) -> dict: ...
    async def get_state(self, provider_id: UUID) -> dict: ...
