"""
Repository Ports (Interfaces)

Architectural Intent:
- Defines port interfaces for all data access operations
- Ports live in domain layer, implementations in infrastructure
- Following Rule 2: Interface-First Development

MCP Integration:
- MCP servers consume these ports via adapters
- MCP tool schemas mirror port method signatures
"""

from abc import ABC, abstractmethod
from uuid import UUID
from typing import Protocol, AsyncIterator
from datetime import datetime

from domain.entities.cloud_provider import CloudProvider, CloudProviderType
from domain.entities.resource import Resource, ResourceType, ResourceState
from domain.entities.agent import Agent


class CloudProviderRepositoryPort(Protocol):
    async def save(self, provider: CloudProvider) -> CloudProvider: ...
    async def get_by_id(self, provider_id: UUID) -> CloudProvider | None: ...
    async def get_by_type(
        self, provider_type: CloudProviderType
    ) -> list[CloudProvider]: ...
    async def get_all(self) -> list[CloudProvider]: ...
    async def delete(self, provider_id: UUID) -> None: ...


class ResourceRepositoryPort(Protocol):
    async def save(self, resource: Resource) -> Resource: ...
    async def get_by_id(self, resource_id: UUID) -> Resource | None: ...
    async def get_by_provider(self, provider_id: UUID) -> list[Resource]: ...
    async def get_by_type(self, resource_type: ResourceType) -> list[Resource]: ...
    async def get_by_state(self, state: ResourceState) -> list[Resource]: ...
    async def get_all(self) -> list[Resource]: ...
    async def delete(self, resource_id: UUID) -> None: ...


class AgentRepositoryPort(Protocol):
    async def save(self, agent: Agent) -> Agent: ...
    async def get_by_id(self, agent_id: UUID) -> Agent | None: ...
    async def get_by_status(self, status: str) -> list[Agent]: ...
    async def get_all(self) -> list[Agent]: ...
    async def delete(self, agent_id: UUID) -> None: ...
